members/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfilePageView, EditProfilePageView, CreateProfilePageView
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('password/', PasswordsChangeView.as_view(template_name ='registration/change-password.html')),
    path('password_success', views.password_success, name="password_success"),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name='show_profile_page'),
    path('<int:pk>/edit_profile_page/', EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page/', CreateProfilePageView.as_view(), name='create_profile_page'),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theblog/urls.py
from.import views
from django.urls import path
from .views import HomeView , RecipieDetailView, AddRecipieView, UpdateRecipieView, DeleteRecipieView, DeleteSuccess, LikeView, AddCommentView #CommentSuccess
from django.conf.urls.static import static
from django.conf import settings
app_name = 'theblog'

urlpatterns = [

    path('',HomeView.as_view(), name="home"),
    path('recipie/<int:pk>', RecipieDetailView.as_view(), name= "recipie-detail"),
    path('add_recipie/',AddRecipieView.as_view(), name='add-recipie'),
    path('recipie/edit/<int:pk>', UpdateRecipieView.as_view(), name='update-recipie'),
    path('recipie/<int:pk>/delete', DeleteRecipieView.as_view(), name='delete-recipie'),
    path('recipie/deleted', DeleteSuccess, name='delete-success'),
    #path('recipie/commented', CommentSuccess, name='comment-success'),
    path('like/<int:pk>', LikeView, name='like_recipie'),
    path('recipie/<int:pk>/comment/', AddCommentView.as_view(), name='add_comment'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yemekdefteri/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('theblog.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

class Recipie(models.Model):
	title = models.CharField(max_length=100)
	header_image = models.ImageField(null=True, blank=True, upload_to="images/")
	chef = models.ForeignKey(User, on_delete= models.CASCADE)
	#recipie_details = models.TextField()
	recipie_details = RichTextField(blank=True, null=True)
	publish_date = models.DateField(auto_now_add=True)
	likes = models.ManyToManyField(User, related_name= 'recipie_post')


	def total_likes(self):
	    return self.likes.count()


	def __str__(self):
		return self.title  +  ' | ' +  str(self.chef)

	def get_absolute_url(self):
	    return reverse('theblog:recipie-detail', args=[str(self.id)])
  
class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
	bio = models.TextField()
	profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile")
	instagram_url = models.CharField(max_length=100, blank=True, null=True)
	facebook_url = models.CharField(max_length=100, blank=True, null=True)
	twitter_url = models.CharField(max_length=100, blank=True, null=True)

	def __str__(self):
		return str(self.user)

	def get_absolute_url(self):
		return reverse('theblog:home')


class Comment(models.Model):
	recipie = models.ForeignKey(Recipie, related_name="comments", on_delete= models.CASCADE)
	name = models.CharField(max_length=100)
	body = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	ordering = ['-id']

	def __str__(self):
		return '%s - %s' % (self.recipie.title, self.name)

theblog/forms.py
from django import forms
from .models import Recipie, Comment


class RecipieForm(forms.ModelForm):
	class Meta:
		model = Recipie
		fields = ('title','chef','recipie_details','header_image')


		widgets = {
                  'title': forms.TextInput(attrs={'class': 'form-control'}),
                  'chef': forms.TextInput(attrs={'class': 'form-control' , 'value':'', 'id':'elder', 'type' : 'hidden'}),
                  #'chef': forms.Select(attrs={'class': 'form-control'}),
                  'recipie_details': forms.Textarea(attrs={'class': 'form-control'}),
         }


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)
		ordering = ['-id']


		widgets = {
                  #'name': forms.TextInput(attrs={'class': 'form-control'}),
                  'body': forms.Textarea(attrs={'class': 'form-control'}),
         }




		

theblog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Recipie, Comment
from .forms import RecipieForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect


def LikeView(request, pk):
	recipie = get_object_or_404(Recipie, id=request.POST.get('recipie_id'))
	liked = False
	if recipie.likes.filter(id=request.user.id).exists():
		recipie.likes.remove(request.user)
		liked = False
	else:
		recipie.likes.add(request.user)
		liked = True

	return HttpResponseRedirect(reverse('theblog:recipie-detail', args=[str(pk)]))



class HomeView(ListView):
	model = Recipie
	template_name= 'theblog/home.html'
	ordering = ['-id']
	#ordering = ['-publish_date']


class RecipieDetailView(DetailView):
	model = Recipie
	template_name = 'theblog/recipie_details.html'

	def get_context_data(self, *args, **kwargs):

		stuff = get_object_or_404(Recipie, id=self.kwargs['pk'])
		total_likes = stuff.total_likes()
		
		liked = False
		if stuff.likes.filter(id=self.request.user.id).exists():
			liked = True

		context = super(RecipieDetailView, self).get_context_data(*args, **kwargs)
		context["total_likes"] =total_likes
		context["liked"] = liked
		return context


class AddRecipieView(CreateView):
	model = Recipie
	form_class = RecipieForm
	template_name = 'theblog/add_recipie.html'

class UpdateRecipieView(UpdateView):
    model = Recipie
    form_class = RecipieForm
    template_name = 'theblog/update_recipie.html'

class DeleteRecipieView(DeleteView):
    model = Recipie
    template_name = 'theblog/delete_recipie.html'
    success_url = reverse_lazy('theblog:delete-success')


def DeleteSuccess(request):
	 return TemplateResponse(request,'theblog/delete_success.html')



class AddCommentView(CreateView):
	model = Comment
	form_class = CommentForm
	template_name = 'theblog/add_comment.html'
	ordering = ['-id']
	def form_valid(self, form):
		form.instance.recipie_id =self.kwargs['pk']
		form.instance.name = self.request.user.username
		return super().form_valid(form)


	def get_success_url(self):
		return reverse_lazy('theblog:recipie-detail', kwargs={'pk':self.kwargs['pk']})

theblog/templates/theblog/add_comment.html
{% extends 'theblog/base.html'  %}
{% block title%}Add comment for recipe{% endblock %}

{%block content%}
       
 {% if user.is_authenticated %}
 {%  if user.profile.id %}
	<h1>Add Comment</h1>

	 <div class="form-group">
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}

		    <button class="btn btn-dark"> Add Comment</button>

	</div>

{% else %}

You have to create a profile in order to add a comment.
{% endif %}
{% else %}

You have to create an account in order to add a comment.

{% endif %}


{% endblock%}

theblog/templates/theblog/add_recipie.html
{% extends 'theblog/base.html'  %}
{% block title%}{{"New Recipe"}}{% endblock %}

{%block content%}
       
 {% if user.is_authenticated %}
 {%  if user.profile.id %}
	<h1>Add Recipe</h1>

	 <div class="form-group">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.media}}
			{{form.as_p}}

		    <button class="btn btn-dark"> Add Recipe</button>

	</div>


	<script>
		var name = "{{ user.id }}";
		document.getElementById("elder").value = name;


	</script>
{% else %}

You have to create a profile in order to add a recipe
{% endif %}
{% else %}

You shall not pass !!!

{% endif %}

{% endblock%}

theblog/templates/theblog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href= "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{%block title%}  Yemekdefteri   {% endblock %}</title>
  </head>
  <body>
    <style>
      body {background-color:  #f9e79f;}
      </style>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'theblog:home'%}"style="color:#f39c12; font-family: verdana;font-size: 300%;border: 8px solid #abb2b9;padding:15px;">Yemekdefteri</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        {% if user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'theblog:add-recipie'%}"style="color:#f1c40f;font-family: verdana;font-size: 150%;margin: 20px;">Add a new Recipe</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"style="color:#f1c40f;font-family: verdana;font-size: 150%;margin: 20px;">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            
            <li>
              <a class="dropdown-item" href="{% url 'edit_profile' %}"style="color:  #d35400  ;font-family: verdana;">Edit User Info</a>
              {%  if user.profile.id %}
              <a class="dropdown-item" href = "{% url 'edit_profile_page' user.profile.id%}"style="color:  #d35400  ;font-family: verdana;">Edit Profile Page </a>
              <a class="dropdown-item" href = "{% url 'show_profile_page' user.profile.id %}"style="color:  #d35400  ;font-family: verdana;">Show Profile Page </a>
                {% else %}
                 <a class="dropdown-item" href = "{% url 'create_profile_page' %}"style="color:  #d35400  ;font-family: verdana;">Create Profile Page </a>
                {% endif %}
            </li>
                        
          </ul>
        </li>

        
        
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"style="color:#f1c40f;"><button style="background-color:  #f1c40f ;font-family: verdana;font-size: 150%;margin: 20px;"button">Logout</button>

          </a>
        </li>
        {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}"style="color:#f1c40f;font-family: verdana;font-size: 150%;margin: 20px;">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}"style="color:#f1c40f;font-family: verdana;font-size: 150%;margin: 20px;">Login</a>
        </li>
        {% endif %} 
        
        
      </ul>
      
    </div>
  
</nav>


    </br></br></br>
<div class="container">
    {%block content%}



    {% endblock%}
   </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

theblog/templates/theblog/comment_success.html
{% extends 'theblog/base.html'  %}
{% block title%}{{"Recipie Deleted"}}{% endblock %}

{%block content%}

<h1>{{ "You have successfully added a comment to the recipe"}}</h1>
<br/>
<br/>       

<a href= "{%url 'theblog:home'%}" class= "btn btn-dark"> Go Back to Home Page</a>


{% endblock%}

theblog/templates/theblog/delete_recipie.html
{% extends 'theblog/base.html'  %}
{% block title%}{{"Delete Recipe"}}{% endblock %}

{%block content%}
       
{% if user.is_authenticated %}
	 {% if user.id == recipie.chef.id %}
	<h1>Delete Recipe</h1>
	</br></br>
	<h3>Delete : {{ recipie.title}} </h3>
	</br></br>
	 <div class="form-group">
		<form method="POST">
			{% csrf_token %}
		    {{form.as_p}}

		    <strong><big> Attention . Deleting means that the recipie will be terminated completely. Before deleting this recipie please be sure !</big></strong>
		    </br></br>
		    <button class="btn btn-dark"> Delete Recipe</button>
	{% endif %}
{% else %}

You shall not pass !!!

{% endif %}

{% endblock%}

</div>

theblog/templates/theblog/delete_success.html
{% extends 'theblog/base.html'  %}
{% block title%}{{"Recipie Deleted"}}{% endblock %}

{%block content%}

<h1>{{ "You have successfully deleted the recipie"}}</h1>
<br/>
<br/>       

<a href= "{%url 'theblog:home'%}" class= "btn btn-dark"> Go Back to Home Page</a>


{% endblock%}

theblog/templates/theblog/home.html
{% extends 'theblog/base.html'  %}

{%block content%}
       

<h1>Recipe List</h1>

<ul>
{% for recipie in object_list %}
 <li><a href= "{%url 'theblog:recipie-detail' recipie.pk %}" class="btn btn-dark">
 	{{ recipie.title}}</a> - Chef : {%  if recipie.chef.profile.id %}
	<a href = "{% url 'show_profile_page' recipie.chef.profile.id %}">{{ recipie.chef.first_name}} {{ recipie.chef.last_name}} </a>
   	{% else %}
   	This chef does not have a profile
   	{% endif %} -  {{recipie.publish_date}}  -
 	 {% if user.is_authenticated %}
	      {% if user.id == recipie.chef.id %}
	 	<xxsmall><a href=  "{%url 'theblog:update-recipie' recipie.pk %}">(Edit)</a></xxsmall>

	 	<xxsmall><a href=  "{%url 'theblog:delete-recipie' recipie.pk %}">(Delete)</a></xxsmall> <br/>
		 {% endif %}
 	{% endif %}
	 {% if recipie.header_image %}
	 <br/>

	<img src="{{ recipie.header_image.url}}"><br/><br/>
	{% endif %}
    {{ recipie.recipie_details|safe|slice:":170" }}
</li>
    
{% endfor%}
</ul>



{% endblock%}

theblog/templates/theblog/recipie_details.html
{% extends 'theblog/base.html'  %}
{% block title%}{{recipie.title}}{% endblock %}

{%block content%}


<h1> {{ recipie.title}}</h1>
<small>By: 
	{%  if recipie.chef.profile.id %}
	<a href = "{% url 'show_profile_page' recipie.chef.profile.id %}">{{ recipie.chef.first_name}} {{ recipie.chef.last_name}} </a>
   	{% else %}
   	This chef does not have a profile
   	{% endif %}

-  {{recipie.publish_date}} </small><xxsmall>
     {% if user.is_authenticated %}
	     {% if user.id == recipie.chef.id %}
			<a href=  "{%url 'theblog:update-recipie' recipie.pk %}">(Edit)</a></xxsmall><xxsmall><a href=  "{%url 'theblog:delete-recipie' recipie.pk %}">(Delete)</a></xxsmall>
		 {%endif%}


	{% endif %}<br/>
<hr>
<br/>
{% if recipie.header_image %}
	<img src="{{ recipie.header_image.url}}"><br/><br/>
{% endif %}
{{ recipie.recipie_details|safe }}
<br/><br/> <hr> <br/>
 {% if user.is_authenticated %}
 <form action= "{% url 'theblog:like_recipie' recipie.pk %}"
 method="POST">
 	{% csrf_token %}
 	{% if liked %}
 		<button type="submit" , name= "recipie_id", value = "{{ recipie.id }}", class ="btn-danger">I don't like this anymore</button>
 	{%else %}
 		<button type="submit" , name= "recipie_id", value = "{{ recipie.id }}", class ="btn btn-dark">Like</button>

 	{% endif %}
</form>
 {%endif%} 


 - {{ total_likes }} Like </br><hr>
 </br></br>


 <h2>Comments...</h2>
</br>

 {% if not recipie.comments.all %}
 	<strong>No comments yet</strong></br></br>
{% if user.is_authenticated and user.profile.id %}
<a href="{% url  'theblog:add_comment' recipie.pk   %}" class= "btn btn-dark"> Add  one</a>
 {%else%}
 <a href="{% url 'register' %}" class= "btn btn-dark">Create an account to add a comment</a>
{% endif %}
 {% else %}
 {% if user.is_authenticated and user.profile.id %}
<a href="{% url  'theblog:add_comment' recipie.pk %}" class= "btn btn-dark"> Add Comment</a>
 {%else%}
 <a href="{% url 'register' %}" class= "btn btn-dark">Create an account to add a comment</a>
{% endif %}
</br></br>


 	{% for comment in recipie.comments.all %}
 		<strong>{{comment.date_added}}   |   {{ comment.name}} : </br> </strong>
 		{{ comment.body}} </br> <hr> </br></br>
 	{% endfor %}
 {% endif %}



</br></br>
<a href= "{%url 'theblog:home'%}" class= "btn btn-dark"> Back</a>


{% endblock %}

theblog/templates/theblog/update_recipie.html
{% extends 'theblog/base.html'  %}
{% block title%}{{"Edit Recipe"}}{% endblock %}

{%block content%}
       
{% if user.is_authenticated %}
	 {% if user.id == recipie.chef.id %}
	<h1>Edit Recipie</h1>

	 <div class="form-group">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.media}}
			{{form.as_p}}

		    <button class="btn btn-dark"> Edit Recipie</button>

	</div>
	{% endif %}
{% else %}

You shall not pass !!!

{% endif %}

{% endblock%}